AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowOrigin: "'http://localhost:3000'"

Resources:
  FindChannelFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: FindChannelFunction
      Handler: no.unit.nva.channel.Handler::handleRequest
      Runtime: java8
      MemorySize: 512
      Events:
        FindChannel:
          Type: Api
          Properties:
            Path: /search
            Method: POST

Outputs:
  FindChannelApi:
    Description: "API Gateway endpoint URL for Prod stage for Find Channel function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/search/"
  FindChannelFunction:
    Description: "Find Channel Lambda Function ARN"
    Value: !GetAtt FindChannelFunction.Arn
  FindChannelFunctionIamRole:
    Description: "Implicit IAM Role created for Find Channel function"
    Value: !GetAtt FindChannelFunctionRole.Arn