AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS

  Sample SAM Template for AWS

Metadata:
  AWS::ServerlessRepo::Application:
    Name: PublicationChannelRegister
    Description: Channel Registry for publications
    Author: Unit
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    Labels: ['${GIT_REPO}', '${CODEBUILD_RESOLVED_SOURCE_VERSION}', '@${BUILD_TIMESTAMP}']
    # SemanticVersion: is set via SAM command line

Parameters:
  CognitoAuthorizerArn:
    Type: String
    Description: Reference to Cognito UserPool for the stage
  CustomDomain:
    Type: String
    Description: Custom API to connect this lambda to
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain

Globals:
  Function:
    Timeout: 20
  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:
  FindChannelApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Models:
        Search:
          type: object
          required:
            - tableId
            - searchTerm
          properties:
            tableId:
              type: integer
            searchTerm:
              type: string

  FindChannelFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: find-channel
      Handler: no.unit.nva.channel.MainHandler::handleRequest
      Runtime: java11
      MemorySize: 1408
      Environment:
        Variables:
          ALLOWED_ORIGIN: '*'
      Events:
        FindChannel:
          Type: Api
          Properties:
            Path: /search
            Method: POST
            RestApiId:
              Ref: FindChannelApi
            RequestModel:
              Model: Search
              Required: true

  FindChannelBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref CustomDomain
      RestApiId: !Ref FindChannelApi
      Stage: !Ref FindChannelApi.Stage
